POST http://localhost:3000/api/clientes
Content-Type: application/json

{
  "nome": "carolsheipada",
  "idade": 19,
  "peso": 65,
  "altura": 163,
  "username": "carolsheipada",
  "password": "senhatop",
  "exercicios": [],
  "refeicoes": []
}