POST http://localhost:3000/api/exercicios
Content-Type: application/json

{
  "tipo": "Musculação",
	"hora": "22:00",
	"duracao": 100,
	"calorias": 300
}

###
GET http://localhost:3000/api/clientes

###
GET http://localhost:3000/api/clientes/64220fbde7fe4e0c442e2205