POST http://localhost:3000/api/clientes
Content-Type: application/json

{
  "username": "caahp",
  "password": "1234",
  "nome": "carol",
  "idade": 19,
  "peso": 65,
  "altura": 163,
  "exercicios": [],
  "refeicoes": []
}

###
GET http://localhost:3000/api/clientes

###
GET http://localhost:3000/api/clientes/64220fbde7fe4e0c442e2205